channels:
- conda-forge
dependencies:
- python=3.11.11
- pip<=25.1
- pip:
  - mlflow==3.1.0
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==24.2
  - pandas==2.2.3
  - psutil==5.9.4
  - pyyaml==6.0.2
  - scikit-learn==1.6.1
  - scipy==1.15.3
  - xgboost==3.0.1
name: mlflow-env
